Tickets/preops 3763
lsst/schedview pull request #35
Opened 2023-10-09 10:13 UTC by emanehab99

Tests were failing because for some reason some bokeh models are owned by multiple documents. This happens when scheduler dashboard and prenight dashboard both run in tests. Resetting bokeh output before and after tests fixes the issue

2023-10-09 14:58 UTC, ehneilsen requested changes
Mostly, this looks good! I just have a few minor stylistic requests.

First, there are some public functions that do not have docstrings. In general, a function should either have a docstring, or marked as private (have a preceeding underscore), or both.

Second, some of the docstrings that are there have their summary sentences on a different line from the opening tripple quote. This messes up some of the doc extraction tools. See https://developer.lsst.io/python/numpydoc.html . 

Finally, there are still a few extraneous "print" statements in there, obviously included for debugging. If they should be there long term, they should probably be logging messages instead.

In each of these cases, I just marked one example with a comment, but there are multiple instances of each.

2023-10-09 14:58 UTC, ehneilsen commented on tests/test_scheduler_dashboard.py
> +        print(TEST_PICKLE)
This print is probably no longer necessary (or logging would be better).

2023-10-09 14:58 UTC, ehneilsen commented on schedview/app/scheduler_dashboard/scheduler_dashboard.py
> +def get_color_palettes():
Consider either indicating that this private (preceded by and underscore), or adding a docstring (if it is not).

2023-10-09 14:58 UTC, ehneilsen commented on schedview/app/scheduler_dashboard/scheduler_dashboard.py
> +        print(f"date in mjd: {self._date_time}")
Is this print still necessary (or should it be replaced by a log message)?

2023-10-09 14:58 UTC, ehneilsen commented on schedview/app/scheduler_dashboard/scheduler_dashboard.py
> +        """
The summary line for a docstring should be on the same line as the initial tripple quote (see https://developer.lsst.io/python/numpydoc.html , in the section whose heading starts with "Docstrings SHOULD begin with".

2023-10-10 14:37 UTC, ehneilsen commented
Can you do a rebase onto main and resolve the resultant merge conflicts?

2023-10-10 23:02 UTC, emanehab99 commented
@ehneilsen Does that look good now? Could it be merged?

2023-10-11 03:21 UTC, emanehab99 commented
> Can you do a rebase onto main and resolve the resultant merge conflicts?

I did. Please let me know if I need to do something different

2023-10-11 03:36 UTC, emanehab99 commented
> Can you do a rebase onto main and resolve the resultant merge conflicts?
Comments addressed. It should be up to date now.

2023-10-11 04:11 UTC, emanehab99 commented
I'm not sure what the ticks and crosses next to commits mean. That's what I did to rebase the branch
```
git checkout main
git pull 
git checkout tickets/PREOPS-3763
git rebase main
git pull
git push
```

2023-10-11 04:27 UTC, timj commented
You made one mistake in:

```
git checkout main
git pull 
git checkout tickets/PREOPS-3763
git rebase main
git pull
git push
```
It should be:
```
git checkout main
git pull 
git checkout tickets/PREOPS-3763
git rebase main
git push -f
```

That `git pull` at the end forces a redownload of the original ticket branch and git makes a merge commit to deal with them being different commits because you had rebased locally.

The `-f` tells git that the local version is the proper one.

2023-10-11 04:37 UTC, emanehab99 commented
> You made one mistake in:
> 
> ```
> git checkout main
> git pull 
> git checkout tickets/PREOPS-3763
> git rebase main
> git pull
> git push
> ```
> 
> It should be:
> 
> ```
> git checkout main
> git pull 
> git checkout tickets/PREOPS-3763
> git rebase main
> git push -f
> ```
> 
> That `git pull` at the end forces a redownload of the original ticket branch and git makes a merge commit to deal with them being different commits because you had rebased locally.
> 
> The `-f` tells git that the local version is the proper one.


Thank you. I've done that now but I'm not happy with the commit history (repeating my commits multiple times). Is there a way to clean it?

2023-10-11 04:39 UTC, timj commented
You can do `git rebase -i main` and squash related commits.

2023-10-11 04:57 UTC, emanehab99 commented
> You can do `git rebase -i main` and squash related commits.


That worked! Looks much better. Thank you so much :)

2023-10-11 14:34 UTC, ehneilsen approved these changes

2023-10-11 22:33 UTC, merged